name: jobApp Backend Actions
on:
  push:
    branches:
      - github-actions
  workflow_dispatch:
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Testing workflow
        run: echo "Workflow works!"
